/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hibernate;

import java.util.Date;

public class App {
    public static void main(String[] args) {
        EventService eventService = new EventServiceImpl();
        eventService.registerEvent(new Date(), "test_event");
    }
}
