/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.guice;

import com.google.inject.Guice;
import com.google.inject.Injector;

public class App {
    public static void main(String[] args) {
        Injector injector = Guice.createInjector(
                new AppModule()
        );

        Foo foo = injector.getInstance(Foo.class);
        foo.hello("test_hello");
    }
}
