ARG SERVICE_FOLDER=serviceX
ARG STARTUP_CLASS=com.serviceX.App

FROM gradle:7.4.1-jdk11 AS build
ARG SERVICE_FOLDER

WORKDIR /$SERVICE_FOLDER

COPY *.gradle ./
COPY app/ app/
COPY gradle/ gradle/
COPY gradlew gradlew

RUN chmod +x gradlew
RUN ./gradlew build

FROM openjdk:11 as runtime
ARG SERVICE_FOLDER
ARG STARTUP_CLASS

WORKDIR /$SERVICE_FOLDER

COPY --from=build /$SERVICE_FOLDER/app/build/distributions/app.tar ./
RUN tar -xvf app.tar

WORKDIR /$SERVICE_FOLDER/app/lib
